---
#- name: Install sasl-saslauthd
#  pkgng: name={{ item }} state=present
#  with_items:
#    - cyrus-sasl-saslauthd

- name: Enable saslauthd
  service: name=saslauthd enabled=yes

- name: Start saslauthd
  service: name=saslauthd state=started

- name: Check to see if sendmail has already been compiled with SASL support
  check_mode: no
  register: sendmail_compile_flags
  ansible.builtin.command:
    cmd: '/usr/sbin/sendmail -bt -d0.1'
    stdin: '/dev/null'

- name: Is SASL compiled in sendmail
  set_fact:
    sasl_compiled_sendmail: "{{ True if 'SASLv2' in sendmail_compile_flags.stdout else False }}"

- name: Display what we found
  debug:
    msg: "sasl_compiled_sendmail is {{ sasl_compiled_sendmail }}"

- name: Check if src is installed
  stat: path=/usr/src/bin
  register: usr_src_bin

- block:
  - name: Download src file
    get_url:
      url: "ftp://ftp.freebsd.org/pub/FreeBSD/releases/amd64/{{ ansible_facts.distribution_version }}-RELEASE/src.txz"
      dest: /src.txz

  - name: Unpack src
    unarchive:
      src: /src.txz
      dest: /
      copy: no
  when: not sasl_compiled_sendmail|bool and not usr_src_bin.stat.exists

- name: Edit /etc/make.conf
  blockinfile:
    dest: /etc/make.conf
    block: |
      SENDMAIL_CFLAGS=-I/usr/local/include/sasl -DSASL
      SENDMAIL_LDFLAGS=-L/usr/local/lib
      SENDMAIL_LDADD=-lsasl2
    backup: yes
    create: yes
  when: not sasl_compiled_sendmail|bool

- name: Compile sendmail
  shell: >
    cd /usr/src/lib/libsmutil &&
    make cleandir && make obj && make &&
    cd /usr/src/lib/libsm &&
    make cleandir && make obj && make && 
    cd /usr/src/usr.sbin/sendmail &&
    make cleandir && make obj && make && make install  
  args:
    creates: /usr/obj/usr/src/usr.sbin/sendmail/sendmail
  when: not sasl_compiled_sendmail|bool
  notify: restart sendmail

- name: Copy Sendmail.conf
  copy: src=Sendmail.conf dest=/usr/local/lib/sasl2/Sendmail.conf mode=0644 backup=yes
  notify: restart saslauthd 
